server:
  port: 9999
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: true

spring:
#数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/work?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: llq
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp

#视图解析

mybatis:
  type-aliases-package: com.work.pojo
  mapper-locations: classpath:/mapper/*.xml


logging:
  level:
    com.work.mapper: debug

